const itemList = [
  { item: '에스더의 기운', idx: 1 },
  { item: '파괴석 결정', idx: 2 },
  { item: '파괴강석', idx: 3 },
  { item: '중급 오레하 융화 재료', idx: 4 },
  { item: '상급 오레하 융화 재료', idx: 5 },
  { item: '위대한 명예의 돌파석', idx: 6 },
  { item: '수호강석', idx: 7 },
  { item: '경이로운 명예의 돌파석', idx: 8 },
  { item: '태양의 은총', idx: 9 },
  { item: '태양의 축복', idx: 10 },
  { item: '태양의 가호', idx: 11 },
  { item: '명예의 파편 주머니(소)', idx: 12 },
  { item: '명예의 파편 주머니(중)', idx: 13 },
  { item: '명예의 파편 주머니(대)', idx: 14 },
  { item: '야금술 : 단조 심화', idx: 15 },
  { item: '재봉술 : 수선 심화', idx: 16 },
  { item: '원한 각인서', idx: 17 },
  { item: '예리한 둔기 각인서', idx: 18 },
  { item: '저주받은 인형 각인서', idx: 19 },
  { item: '절정 각인서', idx: 20 },
  { item: '점화 각인서', idx: 21 },
  { item: '절실한 구원 각인서', idx: 22 },
  { item: '아드레날린 각인서', idx: 23 },
  { item: '잔재된 기운 각인서', idx: 24 },
  { item: '축복의 오라 각인서', idx: 25 },
  { item: '타격의 대가 각인서', idx: 26 },
  { item: '돌격대장 각인서', idx: 27 },
  { item: '광기 각인서', idx: 28 },
  { item: '전문의 각인서', idx: 29 },
  { item: '환류 각인서', idx: 30 },
  { item: '각성 각인서', idx: 31 },
  { item: '버스트 각인서', idx: 32 },
  { item: '피스메이커 각인서', idx: 33 },
  { item: '진화의 유산 각인서', idx: 34 },
  { item: '일격필살 각인서', idx: 35 },
  { item: '극의: 체술 각인서', idx: 36 },
  { item: '질량 증가 각인서', idx: 37 },
  { item: '상급 소환사 각인서', idx: 38 },
  { item: '기습의 대가 각인서', idx: 39 },
  { item: '고독한 기사 각인서', idx: 40 },
  { item: '화력 강화 각인서', idx: 41 },
  { item: '바리케이드 각인서', idx: 42 },
  { item: '초심 각인서', idx: 43 },
  { item: '분노의 망치 각인서', idx: 44 },
  { item: '갈증 각인서', idx: 45 },
  { item: '정기 흡수 각인서', idx: 46 },
  { item: '죽음의 습격 각인서', idx: 47 },
  { item: '속전속결 각인서', idx: 48 },
  { item: '충격 단련 각인서', idx: 49 },
  { item: '정밀 단도 각인서', idx: 50 },
  { item: '달의 소리 각인서', idx: 51 },
  { item: '두 번째 동료 각인서', idx: 52 },
  { item: '역천지체 각인서', idx: 53 },
  { item: '중갑 착용 각인서', idx: 54 },
  { item: '황후의 은총 각인서', idx: 55 },
  { item: '슈퍼 차지 각인서', idx: 56 },
  { item: '중력 수련 각인서', idx: 57 },
  { item: '절제 각인서', idx: 58 },
  { item: '오의난무 각인서', idx: 59 },
  { item: '핸드거너 각인서', idx: 60 },
  { item: '안정된 상태 각인서', idx: 61 },
  { item: '만개 각인서', idx: 62 },
  { item: '회귀 각인서', idx: 63 },
];

const imageItemMatch = {
  에스더의기운: './images/loa_icons/esder.PNG',
  파괴강석: './images/loa_icons/redStoneHigh.PNG',
  파괴석결정: './images/loa_icons/redStoneLow.PNG',
  중급오레하융화재료: './images/loa_icons/middleOreha.PNG',
  상급오레하융화재료: './images/loa_icons/highOreha.PNG',
  위대한명예의돌파석: './images/loa_icons/breakStoneLow.PNG',
  수호강석: './images/loa_icons/blueStoneHigh.PNG',
  경이로운명예의돌파석: './images/loa_icons/breakStoneHigh.PNG',
  태양의은총: './images/loa_icons/sunLow.PNG',
  태양의축복: './images/loa_icons/sunMedium.PNG',
  태양의가호: './images/loa_icons/sunHigh.PNG',
  명예의파편주머니소: './images/loa_icons/fameLow.PNG',
  명예의파편주머니중: './images/loa_icons/fameMedium.PNG',
  명예의파편주머니대: './images/loa_icons/fameHigh.PNG',
  야금술단조심화: './images/loa_icons/accelaratorWeapon.PNG',
  재봉술수선심화: './images/loa_icons/accelaratorArmor.PNG',
};

export { imageItemMatch, itemList };
