const todoData = [
  {
    _id: "5d713a66ec8f2b88b8f830b8",
    user: "5d7a514b5d2c12c7449be045",
    character: "lancemaster",
    characterName: "sept",
    date: "2021-08-01",
    idx: 1,
    chaosRestValue: 60,
    guardianRestValue: 50,
    eponaRestValue: 90,
    chaosDone: 0,
    guardianDone: 0,
    eponaDone: 0,
    guardianWeeklyDone: 3,
    abyssDungeon2: true,
    abyssDungeonWeekly: true,
    rehearsalAndDejavu: ["kukuseitn", "abrel"],
    argos: true,
    baltan: true,
    biakiss: true,
    kukuseitn: true,
    abrel: false,
    attributeChanged: false,
    weeklyAttributeChanged: false, // 쿠크세이튼, 아브렐 리허설
    createdAt: "2021-07-26",
  },
  {
    _id: "5d725a037b292f5f8ceff787",
    user: "5d7a514b5d2c12c7449be042",
    character: "gunslinger",
    characterName: "beyond",
    date: "2021-08-01",
    idx: 2,
    chaosRestValue: 40,
    guardianRestValue: 30,
    eponaRestValue: 70,
    chaosDone: 2,
    guardianDone: 0,
    eponaDone: 0,
    guardianWeeklyDone: 2,
    abyssDungeon2: true,
    abyssDungeonWeekly: true,
    rehearsalAndDejavu: ["kukuseitn", "abrel"],
    argos: true,
    baltan: true,
    biakiss: false,
    kukuseitn: false,
    abrel: false,
    attributeChanged: false,
    weeklyAttributeChanged: false,
    createdAt: "2021-07-28",
  },
  {
    _id: "5d725a037b292f5f8ceff782",
    user: "5d7a514b5d2c12c7449be042",
    character: "gunslinger",
    characterName: "나는접속한다고로존재한다",
    date: "2021-08-01",
    idx: 2,
    chaosRestValue: 40,
    guardianRestValue: 30,
    eponaRestValue: 70,
    chaosDone: 2,
    guardianDone: 0,
    eponaDone: 0,
    guardianWeeklyDone: 2,
    abyssDungeon2: true,
    abyssDungeonWeekly: true,
    rehearsalAndDejavu: ["kukuseitn", "abrel"],
    argos: true,
    baltan: false,
    biakiss: false,
    kukuseitn: false,
    abrel: false,
    attributeChanged: false,
    weeklyAttributeChanged: false,
    createdAt: "2021-07-28",
  },
  {
    _id: "5d725a037b292f5f8ceff785",
    user: "5d7a514b5d2c12c7449be042",
    character: "gunslinger",
    characterName: "beyond",
    date: "2021-08-01",
    idx: 2,
    chaosRestValue: 40,
    guardianRestValue: 30,
    eponaRestValue: 70,
    chaosDone: 2,
    guardianDone: 0,
    eponaDone: 0,
    guardianWeeklyDone: 2,
    abyssDungeon2: true,
    abyssDungeonWeekly: true,
    rehearsalAndDejavu: ["kukuseitn", "abrel"],
    argos: false,
    baltan: true,
    biakiss: false,
    kukuseitn: false,
    abrel: false,
    attributeChanged: false,
    weeklyAttributeChanged: false,
    createdAt: "2021-07-28",
  },
];

export default todoData;
